### PR TITLE
Feat/9p mnt

### PR DESCRIPTION
**Pull request by jgoux**
I activated the required option as per https://github.com/copy/v86/blob/master/docs/linux-9p-image.md using `make linux-menuconfig`.

I linked the custom `linux.conf` to our main `.config` file.

I added instructions to tweak the kernel configuration.

### CODE REVIEW

**Review by burggraf — APPROVED** [review]
Can we move these `copy` lines into the `Dockerfile`?

**Comment by jgoux** [comment]
> Can we move these `copy` lines into the `Dockerfile`?

It would mean we would have to rebuild buildroot each time we want to run it no? Copy is static in the Dockerfile.

**Comment by burggraf** [comment]
> > Can we move these `copy` lines into the `Dockerfile`?
> 
> It would mean we would have to rebuild buildroot each time we want to run it no? Copy is static in the Dockerfile.

It always needs to be run once, so that could happen in `Dockerfile`. You can always run it again from inside the image if you need to change things, no?  This would eliminate that step for people running this themselves.  That's the only reason.

**Comment by jgoux** [comment]
> > > Can we move these `copy` lines into the `Dockerfile`?
> > 
> > 
> > It would mean we would have to rebuild buildroot each time we want to run it no? Copy is static in the Dockerfile.
> 
> It always needs to be run once, so that could happen in `Dockerfile`. You can always run it again from inside the image if you need to change things, no? This would eliminate that step for people running this themselves. That's the only reason.

Alright, we now copy the initial files in the container so we have a `.config` file to start with!

**Review by burggraf — APPROVED** [review]

**Pull request merged**
